### ISSUE TITLE
"How to run this image" cloning error

### ISSUE THREAD

**Issue by stormont** [bigthyme/cv#1]
`git clone git@github.com:bigthyme/cv.git`

This fails due to permissions (I'm not `bigthyme`). A regular clone works:

`git clone https://github.com/bigthyme/cv.git`

**Comment by bigthyme** [comment]
Hi @stormont! 

You should be able to use either protocol; git@ goes through ssh while https goes through http a la port 443. To use `git@`, you need to add your ssh key to github: https://help.github.com/articles/connecting-to-github-with-ssh/

But...most folks will probably be using https so I'll update the readme!
